### ISSUE TITLE
Repeated Food Item Listing

### ISSUE THREAD

**Issue by NguyenNguyenG** [vanshg/BruinMenu-Backend#9]
1) The API is listing repeated food items in each of the stations of a dinning hall. 
2) If no date is inputed, the API returns menu items of the day before not the current day I believe

**Comment by sahilmgandhi** [comment]
Hi Nguyen, 

We fixed the first problem, thank you for pointing that out!
Can you try reproducing the second problem? I cannot reproduce it on my end.
